#!/bin/sh
tmp=$(mktemp)
cat >$tmp <<EOF
BEGIN {

	# Top row -- right-most keys
	m[17]=68;m[18]=70;        m[20]=73;m[21]=75
	    m[31]=69;m[32]=71;m[33]=72;m[34]=74;m[35]=76

	# Top row -- left-most keys
	m[10]=56;m[11]=58;         m[13]=61;m[14]=63;         m[16]=66
	    m[24]=57;m[25]=59;m[26]=60;m[27]=62;m[28]=64;m[29]=65;m[30]=67

	# Bottom row -- right-most keys
	m[44]=56;m[45]=58;        m[47]=61;m[48]=63
	    m[58]=57;m[59]=59;m[60]=60;m[61]=62;

	# Bottom row -- left-most keys
	         m[38]=46;         m[40]=49;m[41]=51;         m[43]=54
	             m[52]=47;m[53]=48;m[54]=50;m[55]=52;m[56]=53;m[57]=55
}

/^KeyPress / {mod=1}
/^KeyRelease / {mod=-1}
/, keycode / {x=\$4; if (x in m) {print mod*m[x]; fflush();}}
EOF

xev | awk -f $tmp | ./midigen

rm $tmp
