#!/bin/sh
tmp=$(mktemp)
cat >$tmp <<EOF
BEGIN {
    	m[11]=58;         m[13]=61;m[14]=63;         m[16]=66;m[17]=68;m[18]=70;
	m[24]=57;m[25]=59;m[26]=60;m[27]=62;m[28]=64;m[29]=65;m[30]=67;m[31]=69;m[32]=71;
}

/^KeyPress / {mod=1}
/^KeyRelease / {mod=-1}
/, keycode / {x=\$4; if (x in m) {print mod*m[x]; fflush();}}
EOF

xev | awk -f $tmp | ./midigen

rm $tmp
