
WXDIR=c:\wxWindows-2.4.2

loopseq.exe: loopseq.obj
	cl /nologo loopseq.obj kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comctl32.lib rpcrt4.lib wsock32.lib $(WXDIR)\lib\wxmswd.lib

loopseq.obj: loopseq.cpp
	cl /nologo /MDd /I$(WXDIR)\include /I$(WXDIR)\lib\mswd /c loopseq.cpp

clean:
	-del /f loopseq.obj

reallyclean: clean
	-del /f loopseq.exe

